FROM node:14

# setup workspace
RUN mkdir -p /app/src
WORKDIR /app/src

# install angular
RUN npm install -g @angular/cli

# copy dependency files
COPY ../myCrossword/client/package*.json /app/src

# install dependencies
RUN npm install

# RUN server
EXPOSE 4200 8080 8081
CMD ["ng", "serve", "--host", "0.0.0.0", "--poll=2000", "--port", "4200", "--disable-host-check"]