# Generated by Django 4.0.5 on 2022-06-18 09:22
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonCount',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name',
                 models.CharField(
                     default='',
                     max_length=70)),
                ('frequency',
                 models.IntegerField()),
                ('pressed',
                 models.BooleanField(
                     default=False)),
            ],
        ),
    ]
