# Generated by Django 4.0.5 on 2022-06-19 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buttoncount',
            name='name',
        ),
    ]
